[workspace]
resolver = "2"
members = [
  "corgboot",
  "corgini",
  "corguart",
]

[workspace.dependencies]
conquer-once = { version = "0.4", default-features = false }
elf = { version = "0.7", default-features = false }
log = { version = "0.4", default-features = false }
qemu-exit = { version = "3", default-features = false }
raw-cpuid = { version = "11", default-features = false }
spinning_top = "0.2"
uefi = { version = "0.23", default-features = false }

corg-ini = { path = "corgini" }
corg-uart = { path = "corguart" }
