[workspace]
resolver = "2"
members = [
  "boot",
  "corgini"
]

[workspace.dependencies]
raw-cpuid = { version = "10.6", default-features = false }
uefi = { version = "0.18", default-features = false }
elf = { version = "0.7", default-features = false }
log = { version = "0.4", default-features = false }
spin = { version = "0.9", default-features = false, features = ["lock_api", "spin_mutex", "rwlock", "once", "lazy", "barrier"] }

corg-ini = { path = "corgini" }
