[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/entry:efi_main",
    "-C", "link-arg=/debug:dwarf", 
    "-C", "link-arg=/base:0x8000000",
    "-C", "link-arg=/fixed",
    "-C", "relocation-model=static", 
    "-C", "code-model=small",
]
